# Generated by Django 4.0.5 on 2022-06-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pywvApp', '0002_delete_category_remove_post_category_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
